LearnSpace/Areas/Teacher/Controllers/AssignmentController.cs
using LearnSpace.Core.Interfaces;
using LearnSpace.Core.Models.Assignment;
using Microsoft.AspNetCore.Mvc;

namespace LearnSpace.Web.Areas.Teacher.Controllers
{
    public class AssignmentController : BaseController
    {
        private readonly IAssignmentService assignmentService;

        public AssignmentController(IAssignmentService _assignmentService)
        {
            assignmentService = _assignmentService;
        }

        [HttpGet]
        public async Task<IActionResult> AllAssignmentsClassTeacher(int classId)
        {
            if (!(await assignmentService.ClassExistsByIdAsync(classId)))
            {
                return RedirectToAction("Error404", "Error");
            }
            var assignments = await assignmentService.GetAllAssignmentsByClassForTeacherAsync(GetUserId(), classId);

            return View(assignments);
        }

        [HttpGet]
        public async Task<IActionResult> AssignmentInfoForTeacher(int id)
        {
            if (!(await assignmentService.ExistsByIdAsync(id)))
            {
                return RedirectToAction("Error404", "Error");
            }
            var assignment = await assignmentService.GetAssignmentInfoForTeacherAsync(id);

            return View(assignment);
        }

        [HttpGet]
        public async Task<IActionResult> CreateAssignment(int classId)
        {
            if (!(await assignmentService.ClassExistsByIdAsync(classId)))
            {
                return RedirectToAction("Error404", "Error");
            }
            var model = new CreateAssignmentFormModel
            {
                ClassId = classId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAssignment(CreateAssignmentFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await assignmentService.CreateAssignment(model);

            return RedirectToAction(nameof(AllAssignmentsClassTeacher), new { classId = model.ClassId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAssignment(int id)
        {
            if (!(await assignmentService.ExistsByIdAsync(id)))
            {
                return RedirectToAction("Error404", "Error");
            }
            var classId = await assignmentService.DeleteAssignment(id);

            return RedirectToAction(nameof(AllAssignmentsClassTeacher), new { classId = classId });
        }
    }
}

LearnSpace/Areas/Teacher/Controllers/BaseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static LearnSpace.Web.Areas.Teacher.Constants.TeacherConstants;

namespace LearnSpace.Web.Areas.Teacher.Controllers
{
    [Area(AreaName)]
    [Authorize(Roles = TeacherRole)]
    public class BaseController : Controller
    {
        protected string GetUserId()
        {
            return User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }
    }
}

LearnSpace/Areas/Teacher/Controllers/ClassController.cs
using LearnSpace.Core.Interfaces;
using LearnSpace.Core.Models.Class;
using LearnSpace.Core.Services;
using Microsoft.AspNetCore.Mvc;

namespace LearnSpace.Web.Areas.Teacher.Controllers
{
    public class ClassController : BaseController
    {
        private readonly IClassService classService;

        public ClassController(IClassService _classService)
        {
            classService = _classService;
        }

        [HttpGet]
        public async Task<IActionResult> AllClassesForTeacher()
        {
            var list = await classService.GetAllClassesForTeacherAsync(GetUserId());

            return View(list);
        }

        [HttpGet]
        public IActionResult CreateClass()
        {
            var model = classService.GetCreateClassModel(GetUserId());

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> CreateClass(CreateClassModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await classService.CreateClassAsync(model);

            return RedirectToAction(nameof(AllClassesForTeacher));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteClass(int id)
        {
            if (!(await classService.ExistsByIdAsync(id)))
            {
                return RedirectToAction("Error404", "Error");
            }
            await classService.DeleteClassAsync(id);

            return RedirectToAction(nameof(AllClassesForTeacher));
        }
    }
}

LearnSpace/Areas/Teacher/Controllers/GradeController.cs
using LearnSpace.Core.Interfaces;
using LearnSpace.Core.Models.Grade;
using Microsoft.AspNetCore.Mvc;

namespace LearnSpace.Web.Areas.Teacher.Controllers
{

    public class GradeController : BaseController
    {
        private readonly IGradeService gradeService;

        public GradeController(IGradeService _gradeService)
        {
            gradeService = _gradeService;
        }

        [HttpGet]
        public async Task<IActionResult> GradeInfo(int id)
        {
            if (!(await gradeService.ExistsByIdAsync(id))) 
            {
                return RedirectToAction("Error404", "Error");
            }
            var grade = await gradeService.GetGradeInfoAsync(id);

            return View(grade);
        }
        [HttpGet]
        public async Task<IActionResult> AddGrade(int classId, string studentId)
        {
            if (!(await gradeService.UserExistsByIdAsync(studentId)))
            {
                return RedirectToAction("Error404", "Error");
            }

            if (!(await gradeService.ClassExistsByIdAsync(classId)))
            {
                return RedirectToAction("Error404", "Error");
            }

            var model = await gradeService.GetAddGradeModelAsync(classId, studentId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddGrade(CreateGradeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await gradeService.CreateGradeAsync(model);

            return RedirectToAction("GradeBook", "Teacher", new { classId = model.CourseId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteGrade(int gradeId)
        {
            if (!(await gradeService.ExistsByIdAsync(gradeId)))
            {
                return RedirectToAction("Error404", "Error");
            }
            var classid = await gradeService.DeleteGradeAsync(gradeId);

            return RedirectToAction("GradeBook", "Teacher", new { classId = classid });
        }


    }
}

LearnSpace/Areas/Teacher/Controllers/SubmissionController.cs
using LearnSpace.Core.Interfaces;
using LearnSpace.Web.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace LearnSpace.Web.Areas.Teacher.Controllers
{
    public class SubmissionController : BaseController
    {
        private readonly ISubmissionService submissionService;

        public SubmissionController(ISubmissionService _submissionService)
        {
            submissionService = _submissionService;
        }
        [HttpGet]
        public async Task<IActionResult> AllSubmissionsForAssignment(int assignmentId)
        {
            if (!(await submissionService.AssignmentExistsByIdAsync(assignmentId))) 
            {
                return RedirectToAction("Error404", "Error");
            }
            var model = await submissionService.GetAllSubmissionsForAssignmentAsync(assignmentId);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DownloadFile(int submissionId)
        {
            if (!(await submissionService.ExistsByIdAsync(submissionId)))
            {
                return RedirectToAction("Error404", "Error");
            }

            var model = await submissionService.GetFileBySubmissionIdAsync(submissionId);

            if (model == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            return File(model.FileContent, model.FileType, model.FileName);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSubmission(int submissionId, int assignmentId)
        {

            if (!(await submissionService.ExistsByIdAsync(submissionId)))
            {
                return RedirectToAction("Error404", "Error");
            }
            await submissionService.DeleteSubmissionIdAsync(submissionId);
            if (assignmentId != 0)
            {
                if (!(await submissionService.AssignmentExistsByIdAsync(assignmentId)))
                {
                    return RedirectToAction("Error404", "Error");
                }
                return RedirectToAction(nameof(AllSubmissionsForAssignment), new { assignmentId });
            }
            else 
            {
                return RedirectToAction(nameof(AllSubmissionsForTeacher));
            }
        }

        [HttpGet]
        public async Task<IActionResult> AllSubmissionsForTeacher()
        {
            var model = await submissionService.GetAllSubmissionsForTeacherAsync(GetUserId());

            return View(model);
        }
    }
}

LearnSpace/Areas/Teacher/Controllers/TeacherController.cs
using LearnSpace.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LearnSpace.Web.Areas.Teacher.Controllers
{
    public class TeacherController : BaseController
    {
        private readonly ITeacherService teacherService;

        public TeacherController(ITeacherService _teacherService)
        {
            teacherService = _teacherService;
        }
        [HttpGet]
        public async Task<IActionResult> Dashboard()
        {
            var model = await teacherService.GetTeacherDashboardInformationAsync(GetUserId());

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> GradeBook(int classId)
        {
            if (!(await teacherService.ClassExistsByIdAsync(classId))) 
            {
                return RedirectToAction("Error404", "Error");
            }
            var model = await teacherService.GetGradeBookByClassAsync(GetUserId(), classId);

            return View(model);
        }
    }
}

LearnSpace/Areas/Teacher/Views/Teacher/Dashboard.cshtml
@model TeacherDashboardModel

@{
    ViewBag.Title = "Dashboard";
}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div id="dashboardTeacher" class="d-flex flex-column">
    <div class="text-center text-capitalize fs-4 text-white color-purple-dashboard w-auto m-2">
        @Model.FullName
    </div>
    <div class="container">
        <div class="d-flex flex-row">
            <div class="color-blue m-2 w-100 text-white">
                <h1 class="text-center" style="margin-top: 5px;">@Model.TotalStudentsEnrolled</h1>
                <p class="h4 text-center">Total Students Enrolled</p>
            </div>

            <div class="color-red m-2 w-100 text-white">
                <h1 class="text-center">@Model.AssignmentCount</h1>
                <p class="h4 text-center">Total Assignments</p>
            </div>
        </div>

        <div class="d-flex flex-row">
            <div class="color-green m-2 w-100 text-white">
                <h1 class="text-center">@Model.WaitingSubmissions</h1>
                <p class="h4 text-center">Pending Submissions</p>
            </div>
        </div>
    </div>

   @*  <div class="d-flex justify-content-center mb-5 mt-2">
        <div class="charBox">
            <canvas id="lineChart" class="w-100"></canvas>
        </div>
    </div> *@
</div>

<style>
    .charBox {
        width: 600px;
        padding: 20px;
        border-radius: 20px;
        border: solid 3px rgba(54, 162, 235, 1);
        background: white;
    }

    .color-blue {
        background-color: #007bff;
        border-radius: 8px;
        padding: 20px;
    }

    .color-red {
        background-color: #dc3545;
        border-radius: 8px;
        padding: 20px;
    }

    .color-green {
        background-color: #28a745;
        border-radius: 8px;
        padding: 20px;
    }

    .color-purple-dashboard {
        background-color: #6f42c1;
        padding: 10px;
        border-radius: 8px;
    }
</style>

<script>
    // Function to fetch chart data and render the chart
    async function fetchAndRenderChart() {
        try {
            // Mock example of data for rendering a chart
            const chartData = @Html.Raw(Json.Serialize(new List<dynamic>
                {
                new { Date = "2023-12-01", Submissions = 10 },
                new { Date = "2023-12-02", Submissions = 15 },
                new { Date = "2023-12-03", Submissions = 8 }
                }));

            // Extract labels (dates) and data points (submissions count)
            const labels = chartData.map(item => item.Date);
            const dataPoints = chartData.map(item => item.Submissions);

            // Chart.js configuration
            const data = {
                labels: labels,
                datasets: [{
                    label: 'Submissions Over Time',
                    data: dataPoints,
                    fill: false,
                    borderColor: 'rgb(75, 192, 192)',
                    tension: 0.1
                }]
            };

            const config = {
                type: 'line',
                data: data,
                options: {
                    responsive: true,
                    scales: {
                        x: {
                            title: {
                                display: true,
                                text: 'Date'
                            }
                        },
                        y: {
                            title: {
                                display: true,
                                text: 'Submissions'
                            },
                            beginAtZero: true
                        }
                    }
                }
            };

            // Render the chart in the canvas element
            new Chart(document.getElementById('lineChart'), config);

        } catch (error) {
            console.error('Error rendering chart:', error);
        }
    }

    // Call the function to fetch and render the chart on page load
    fetchAndRenderChart();
</script>

LearnSpace/Areas/Teacher/Views/Teacher/GradeBook.cshtml
@model GradeBookViewModel

@{
    ViewBag.Title = "Grade Book";
}

<div class="container mt-5">
    <h2 class="mb-4 text-center" style="font-size:40px; font-weight: 700;">@ViewBag.Title</h2>
    <p class="text-muted">Total Grades: <strong>@Model.List.SelectMany(s => s.Grades).Count()</strong></p>

    @if (Model.List == null || !Model.List.Any())
    {
        <div class="alert alert-warning text-center">No grades available to display.</div>
    }
    else
    {
        <table class="table table-hover table-bordered" style="border: 3px solid black;">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Student Name</th>
                    <th scope="col">Grades</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var student in Model.List)
                {
                    <tr>
                        <td class="fw-bold">@student.StudentName</td>
                        <td>
                            @if (student.Grades.Any())
                            {
                                <ul class="list-unstyled d-flex flex-row align-content-center flex-wrap mb-0">
                                    @foreach (var grade in student.Grades)
                                    {
                                        <li class="me-2 mb-2">
                                            <a asp-controller="Grade" asp-action="GradeInfo" asp-route-id="@grade.Id" class="text-decoration-none">
                                                <div class="grade-box text-white text-center fw-bold"
                                                     style="width: 50px; height: 50px; line-height: 50px; border-radius: 5px; background-color: @(GetGradeColor(grade.Score)); font-size: 1em;">
                                                    @grade.Score
                                                </div>
                                            </a>
                                        </li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <span>No grades recorded</span>
                            }
                        </td>
                        <td>
                            <!-- Add Grade Action -->
                            <a asp-controller="Grade" asp-action="AddGrade" asp-route-studentId="@student.StudentId" asp-route-classId="@Model.ClassId"
                               class="btn btn-sm btn-info">
                                Add Grade
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

@section Scripts {
    <script>
        // Optional: Add any JS logic here if needed for dynamic interactions.
    </script>
}

@functions {
    // Helper method to calculate the background color based on the grade score
    public string GetGradeColor(double score)
    {
        if (score <= 2.5) return "#dc3545"; // Red for lowest scores
        if (score <= 3) return "#fd7e14"; // Orange
        if (score <= 4) return "#ffc107"; // Yellow
        if (score <= 5) return "#4169E1"; // Light blue
        return "#198754";               // Dark green for highest scores
    }
}